-- migrate:up
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA app TO app_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA api TO api_user;

-- migrate:down
REVOKE SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA app FROM app_user;
REVOKE SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA api TO api_user;