/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as PrivateRouteImport } from './routes/_private'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as ApiUploadthingRouteImport } from './routes/api/uploadthing'
import { Route as PublicDemoRouteImport } from './routes/_public/demo'
import { Route as PrivateStorageRouteImport } from './routes/_private/storage'
import { Route as PrivateProfileRouteImport } from './routes/_private/profile'
import { Route as PrivateBillingRouteImport } from './routes/_private/billing'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthSignoutRouteImport } from './routes/_auth/signout'
import { Route as AuthSigninRouteImport } from './routes/_auth/signin'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as PrivateNewPagesProjectsIndexRouteImport } from './routes/_private/new-pages/projects.index'
import { Route as PrivateNewPagesProjectsProjectIdRouteImport } from './routes/_private/new-pages/projects.$projectId'
import { Route as PrivateNewPagesProjectsProjectIdDocumentsRouteImport } from './routes/_private/new-pages/projects.$projectId_.documents'
import { Route as PrivateNewPagesProjectsProjectIdDashboardRouteImport } from './routes/_private/new-pages/projects.$projectId_.dashboard'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRoute = PrivateRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const ApiUploadthingRoute = ApiUploadthingRouteImport.update({
  id: '/api/uploadthing',
  path: '/api/uploadthing',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicDemoRoute = PublicDemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => PublicRoute,
} as any)
const PrivateStorageRoute = PrivateStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateProfileRoute = PrivateProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateBillingRoute = PrivateBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => PrivateRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignoutRoute = AuthSignoutRouteImport.update({
  id: '/signout',
  path: '/signout',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateNewPagesProjectsIndexRoute =
  PrivateNewPagesProjectsIndexRouteImport.update({
    id: '/new-pages/projects/',
    path: '/new-pages/projects/',
    getParentRoute: () => PrivateRoute,
  } as any)
const PrivateNewPagesProjectsProjectIdRoute =
  PrivateNewPagesProjectsProjectIdRouteImport.update({
    id: '/new-pages/projects/$projectId',
    path: '/new-pages/projects/$projectId',
    getParentRoute: () => PrivateRoute,
  } as any)
const PrivateNewPagesProjectsProjectIdDocumentsRoute =
  PrivateNewPagesProjectsProjectIdDocumentsRouteImport.update({
    id: '/new-pages/projects/$projectId_/documents',
    path: '/new-pages/projects/$projectId/documents',
    getParentRoute: () => PrivateRoute,
  } as any)
const PrivateNewPagesProjectsProjectIdDashboardRoute =
  PrivateNewPagesProjectsProjectIdDashboardRouteImport.update({
    id: '/new-pages/projects/$projectId_/dashboard',
    path: '/new-pages/projects/$projectId/dashboard',
    getParentRoute: () => PrivateRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/signin': typeof AuthSigninRoute
  '/signout': typeof AuthSignoutRoute
  '/signup': typeof AuthSignupRoute
  '/billing': typeof PrivateBillingRoute
  '/profile': typeof PrivateProfileRoute
  '/storage': typeof PrivateStorageRoute
  '/demo': typeof PublicDemoRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/new-pages/projects/$projectId': typeof PrivateNewPagesProjectsProjectIdRoute
  '/new-pages/projects/': typeof PrivateNewPagesProjectsIndexRoute
  '/new-pages/projects/$projectId/dashboard': typeof PrivateNewPagesProjectsProjectIdDashboardRoute
  '/new-pages/projects/$projectId/documents': typeof PrivateNewPagesProjectsProjectIdDocumentsRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/signin': typeof AuthSigninRoute
  '/signout': typeof AuthSignoutRoute
  '/signup': typeof AuthSignupRoute
  '/billing': typeof PrivateBillingRoute
  '/profile': typeof PrivateProfileRoute
  '/storage': typeof PrivateStorageRoute
  '/demo': typeof PublicDemoRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/new-pages/projects/$projectId': typeof PrivateNewPagesProjectsProjectIdRoute
  '/new-pages/projects': typeof PrivateNewPagesProjectsIndexRoute
  '/new-pages/projects/$projectId/dashboard': typeof PrivateNewPagesProjectsProjectIdDashboardRoute
  '/new-pages/projects/$projectId/documents': typeof PrivateNewPagesProjectsProjectIdDocumentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_private': typeof PrivateRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_auth/signin': typeof AuthSigninRoute
  '/_auth/signout': typeof AuthSignoutRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_private/billing': typeof PrivateBillingRoute
  '/_private/profile': typeof PrivateProfileRoute
  '/_private/storage': typeof PrivateStorageRoute
  '/_public/demo': typeof PublicDemoRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/_public/': typeof PublicIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_private/new-pages/projects/$projectId': typeof PrivateNewPagesProjectsProjectIdRoute
  '/_private/new-pages/projects/': typeof PrivateNewPagesProjectsIndexRoute
  '/_private/new-pages/projects/$projectId_/dashboard': typeof PrivateNewPagesProjectsProjectIdDashboardRoute
  '/_private/new-pages/projects/$projectId_/documents': typeof PrivateNewPagesProjectsProjectIdDocumentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/signout'
    | '/signup'
    | '/billing'
    | '/profile'
    | '/storage'
    | '/demo'
    | '/api/uploadthing'
    | '/api/auth/$'
    | '/new-pages/projects/$projectId'
    | '/new-pages/projects/'
    | '/new-pages/projects/$projectId/dashboard'
    | '/new-pages/projects/$projectId/documents'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/signout'
    | '/signup'
    | '/billing'
    | '/profile'
    | '/storage'
    | '/demo'
    | '/api/uploadthing'
    | '/api/auth/$'
    | '/new-pages/projects/$projectId'
    | '/new-pages/projects'
    | '/new-pages/projects/$projectId/dashboard'
    | '/new-pages/projects/$projectId/documents'
  id:
    | '__root__'
    | '/_auth'
    | '/_private'
    | '/_public'
    | '/_auth/signin'
    | '/_auth/signout'
    | '/_auth/signup'
    | '/_private/billing'
    | '/_private/profile'
    | '/_private/storage'
    | '/_public/demo'
    | '/api/uploadthing'
    | '/_public/'
    | '/api/auth/$'
    | '/_private/new-pages/projects/$projectId'
    | '/_private/new-pages/projects/'
    | '/_private/new-pages/projects/$projectId_/dashboard'
    | '/_private/new-pages/projects/$projectId_/documents'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  PrivateRoute: typeof PrivateRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  ApiUploadthingRoute: typeof ApiUploadthingRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/api/uploadthing': {
      id: '/api/uploadthing'
      path: '/api/uploadthing'
      fullPath: '/api/uploadthing'
      preLoaderRoute: typeof ApiUploadthingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/demo': {
      id: '/_public/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof PublicDemoRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_private/storage': {
      id: '/_private/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof PrivateStorageRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/profile': {
      id: '/_private/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof PrivateProfileRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/billing': {
      id: '/_private/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof PrivateBillingRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signout': {
      id: '/_auth/signout'
      path: '/signout'
      fullPath: '/signout'
      preLoaderRoute: typeof AuthSignoutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signin': {
      id: '/_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/new-pages/projects/': {
      id: '/_private/new-pages/projects/'
      path: '/new-pages/projects'
      fullPath: '/new-pages/projects/'
      preLoaderRoute: typeof PrivateNewPagesProjectsIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/new-pages/projects/$projectId': {
      id: '/_private/new-pages/projects/$projectId'
      path: '/new-pages/projects/$projectId'
      fullPath: '/new-pages/projects/$projectId'
      preLoaderRoute: typeof PrivateNewPagesProjectsProjectIdRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/new-pages/projects/$projectId_/documents': {
      id: '/_private/new-pages/projects/$projectId_/documents'
      path: '/new-pages/projects/$projectId/documents'
      fullPath: '/new-pages/projects/$projectId/documents'
      preLoaderRoute: typeof PrivateNewPagesProjectsProjectIdDocumentsRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/new-pages/projects/$projectId_/dashboard': {
      id: '/_private/new-pages/projects/$projectId_/dashboard'
      path: '/new-pages/projects/$projectId/dashboard'
      fullPath: '/new-pages/projects/$projectId/dashboard'
      preLoaderRoute: typeof PrivateNewPagesProjectsProjectIdDashboardRouteImport
      parentRoute: typeof PrivateRoute
    }
  }
}

interface AuthRouteChildren {
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignoutRoute: typeof AuthSignoutRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSigninRoute: AuthSigninRoute,
  AuthSignoutRoute: AuthSignoutRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PrivateRouteChildren {
  PrivateBillingRoute: typeof PrivateBillingRoute
  PrivateProfileRoute: typeof PrivateProfileRoute
  PrivateStorageRoute: typeof PrivateStorageRoute
  PrivateNewPagesProjectsProjectIdRoute: typeof PrivateNewPagesProjectsProjectIdRoute
  PrivateNewPagesProjectsIndexRoute: typeof PrivateNewPagesProjectsIndexRoute
  PrivateNewPagesProjectsProjectIdDashboardRoute: typeof PrivateNewPagesProjectsProjectIdDashboardRoute
  PrivateNewPagesProjectsProjectIdDocumentsRoute: typeof PrivateNewPagesProjectsProjectIdDocumentsRoute
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateBillingRoute: PrivateBillingRoute,
  PrivateProfileRoute: PrivateProfileRoute,
  PrivateStorageRoute: PrivateStorageRoute,
  PrivateNewPagesProjectsProjectIdRoute: PrivateNewPagesProjectsProjectIdRoute,
  PrivateNewPagesProjectsIndexRoute: PrivateNewPagesProjectsIndexRoute,
  PrivateNewPagesProjectsProjectIdDashboardRoute:
    PrivateNewPagesProjectsProjectIdDashboardRoute,
  PrivateNewPagesProjectsProjectIdDocumentsRoute:
    PrivateNewPagesProjectsProjectIdDocumentsRoute,
}

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren)

interface PublicRouteChildren {
  PublicDemoRoute: typeof PublicDemoRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicDemoRoute: PublicDemoRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  PrivateRoute: PrivateRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  ApiUploadthingRoute: ApiUploadthingRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
