/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as PrivateRouteImport } from './routes/_private'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as ApiUploadthingRouteImport } from './routes/api/uploadthing'
import { Route as ApiReleaseLockRouteImport } from './routes/api/release-lock'
import { Route as ApiPdfUploadRouteImport } from './routes/api/pdf-upload'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as PublicPricingRouteImport } from './routes/_public/pricing'
import { Route as PublicDemoRouteImport } from './routes/_public/demo'
import { Route as PrivateProfileRouteImport } from './routes/_private/profile'
import { Route as PrivateBillingRouteImport } from './routes/_private/billing'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthSignoutRouteImport } from './routes/_auth/signout'
import { Route as AuthSigninRouteImport } from './routes/_auth/signin'
import { Route as PrivateProjectsIndexRouteImport } from './routes/_private/projects.index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as PrivateProjectsProjectIdRouteImport } from './routes/_private/projects.$projectId'
import { Route as PrivateProjectsProjectIdLabellingRouteImport } from './routes/_private/projects.$projectId_.labelling'
import { Route as PrivateProjectsProjectIdEntity_typesRouteImport } from './routes/_private/projects.$projectId_.entity_types'
import { Route as PrivateProjectsProjectIdEngineeringRouteImport } from './routes/_private/projects.$projectId_.engineering'
import { Route as PrivateProjectsProjectIdDocumentsRouteImport } from './routes/_private/projects.$projectId_.documents'
import { Route as PrivateProjectsProjectIdDashboardRouteImport } from './routes/_private/projects.$projectId_.dashboard'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRoute = PrivateRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const ApiUploadthingRoute = ApiUploadthingRouteImport.update({
  id: '/api/uploadthing',
  path: '/api/uploadthing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReleaseLockRoute = ApiReleaseLockRouteImport.update({
  id: '/api/release-lock',
  path: '/api/release-lock',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPdfUploadRoute = ApiPdfUploadRouteImport.update({
  id: '/api/pdf-upload',
  path: '/api/pdf-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicPricingRoute = PublicPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDemoRoute = PublicDemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => PublicRoute,
} as any)
const PrivateProfileRoute = PrivateProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateBillingRoute = PrivateBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => PrivateRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignoutRoute = AuthSignoutRouteImport.update({
  id: '/signout',
  path: '/signout',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRoute,
} as any)
const PrivateProjectsIndexRoute = PrivateProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => PrivateRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateProjectsProjectIdRoute =
  PrivateProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => PrivateRoute,
  } as any)
const PrivateProjectsProjectIdLabellingRoute =
  PrivateProjectsProjectIdLabellingRouteImport.update({
    id: '/projects/$projectId_/labelling',
    path: '/projects/$projectId/labelling',
    getParentRoute: () => PrivateRoute,
  } as any)
const PrivateProjectsProjectIdEntity_typesRoute =
  PrivateProjectsProjectIdEntity_typesRouteImport.update({
    id: '/projects/$projectId_/entity_types',
    path: '/projects/$projectId/entity_types',
    getParentRoute: () => PrivateRoute,
  } as any)
const PrivateProjectsProjectIdEngineeringRoute =
  PrivateProjectsProjectIdEngineeringRouteImport.update({
    id: '/projects/$projectId_/engineering',
    path: '/projects/$projectId/engineering',
    getParentRoute: () => PrivateRoute,
  } as any)
const PrivateProjectsProjectIdDocumentsRoute =
  PrivateProjectsProjectIdDocumentsRouteImport.update({
    id: '/projects/$projectId_/documents',
    path: '/projects/$projectId/documents',
    getParentRoute: () => PrivateRoute,
  } as any)
const PrivateProjectsProjectIdDashboardRoute =
  PrivateProjectsProjectIdDashboardRouteImport.update({
    id: '/projects/$projectId_/dashboard',
    path: '/projects/$projectId/dashboard',
    getParentRoute: () => PrivateRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/signin': typeof AuthSigninRoute
  '/signout': typeof AuthSignoutRoute
  '/signup': typeof AuthSignupRoute
  '/billing': typeof PrivateBillingRoute
  '/profile': typeof PrivateProfileRoute
  '/demo': typeof PublicDemoRoute
  '/pricing': typeof PublicPricingRoute
  '/api/chat': typeof ApiChatRoute
  '/api/pdf-upload': typeof ApiPdfUploadRoute
  '/api/release-lock': typeof ApiReleaseLockRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/projects/$projectId': typeof PrivateProjectsProjectIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/projects/': typeof PrivateProjectsIndexRoute
  '/projects/$projectId/dashboard': typeof PrivateProjectsProjectIdDashboardRoute
  '/projects/$projectId/documents': typeof PrivateProjectsProjectIdDocumentsRoute
  '/projects/$projectId/engineering': typeof PrivateProjectsProjectIdEngineeringRoute
  '/projects/$projectId/entity_types': typeof PrivateProjectsProjectIdEntity_typesRoute
  '/projects/$projectId/labelling': typeof PrivateProjectsProjectIdLabellingRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/signin': typeof AuthSigninRoute
  '/signout': typeof AuthSignoutRoute
  '/signup': typeof AuthSignupRoute
  '/billing': typeof PrivateBillingRoute
  '/profile': typeof PrivateProfileRoute
  '/demo': typeof PublicDemoRoute
  '/pricing': typeof PublicPricingRoute
  '/api/chat': typeof ApiChatRoute
  '/api/pdf-upload': typeof ApiPdfUploadRoute
  '/api/release-lock': typeof ApiReleaseLockRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/projects/$projectId': typeof PrivateProjectsProjectIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/projects': typeof PrivateProjectsIndexRoute
  '/projects/$projectId/dashboard': typeof PrivateProjectsProjectIdDashboardRoute
  '/projects/$projectId/documents': typeof PrivateProjectsProjectIdDocumentsRoute
  '/projects/$projectId/engineering': typeof PrivateProjectsProjectIdEngineeringRoute
  '/projects/$projectId/entity_types': typeof PrivateProjectsProjectIdEntity_typesRoute
  '/projects/$projectId/labelling': typeof PrivateProjectsProjectIdLabellingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_private': typeof PrivateRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_auth/signin': typeof AuthSigninRoute
  '/_auth/signout': typeof AuthSignoutRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_private/billing': typeof PrivateBillingRoute
  '/_private/profile': typeof PrivateProfileRoute
  '/_public/demo': typeof PublicDemoRoute
  '/_public/pricing': typeof PublicPricingRoute
  '/api/chat': typeof ApiChatRoute
  '/api/pdf-upload': typeof ApiPdfUploadRoute
  '/api/release-lock': typeof ApiReleaseLockRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/_public/': typeof PublicIndexRoute
  '/_private/projects/$projectId': typeof PrivateProjectsProjectIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_private/projects/': typeof PrivateProjectsIndexRoute
  '/_private/projects/$projectId_/dashboard': typeof PrivateProjectsProjectIdDashboardRoute
  '/_private/projects/$projectId_/documents': typeof PrivateProjectsProjectIdDocumentsRoute
  '/_private/projects/$projectId_/engineering': typeof PrivateProjectsProjectIdEngineeringRoute
  '/_private/projects/$projectId_/entity_types': typeof PrivateProjectsProjectIdEntity_typesRoute
  '/_private/projects/$projectId_/labelling': typeof PrivateProjectsProjectIdLabellingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/signout'
    | '/signup'
    | '/billing'
    | '/profile'
    | '/demo'
    | '/pricing'
    | '/api/chat'
    | '/api/pdf-upload'
    | '/api/release-lock'
    | '/api/uploadthing'
    | '/projects/$projectId'
    | '/api/auth/$'
    | '/projects/'
    | '/projects/$projectId/dashboard'
    | '/projects/$projectId/documents'
    | '/projects/$projectId/engineering'
    | '/projects/$projectId/entity_types'
    | '/projects/$projectId/labelling'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/signout'
    | '/signup'
    | '/billing'
    | '/profile'
    | '/demo'
    | '/pricing'
    | '/api/chat'
    | '/api/pdf-upload'
    | '/api/release-lock'
    | '/api/uploadthing'
    | '/projects/$projectId'
    | '/api/auth/$'
    | '/projects'
    | '/projects/$projectId/dashboard'
    | '/projects/$projectId/documents'
    | '/projects/$projectId/engineering'
    | '/projects/$projectId/entity_types'
    | '/projects/$projectId/labelling'
  id:
    | '__root__'
    | '/_auth'
    | '/_private'
    | '/_public'
    | '/_auth/signin'
    | '/_auth/signout'
    | '/_auth/signup'
    | '/_private/billing'
    | '/_private/profile'
    | '/_public/demo'
    | '/_public/pricing'
    | '/api/chat'
    | '/api/pdf-upload'
    | '/api/release-lock'
    | '/api/uploadthing'
    | '/_public/'
    | '/_private/projects/$projectId'
    | '/api/auth/$'
    | '/_private/projects/'
    | '/_private/projects/$projectId_/dashboard'
    | '/_private/projects/$projectId_/documents'
    | '/_private/projects/$projectId_/engineering'
    | '/_private/projects/$projectId_/entity_types'
    | '/_private/projects/$projectId_/labelling'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  PrivateRoute: typeof PrivateRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  ApiPdfUploadRoute: typeof ApiPdfUploadRoute
  ApiReleaseLockRoute: typeof ApiReleaseLockRoute
  ApiUploadthingRoute: typeof ApiUploadthingRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/api/uploadthing': {
      id: '/api/uploadthing'
      path: '/api/uploadthing'
      fullPath: '/api/uploadthing'
      preLoaderRoute: typeof ApiUploadthingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/release-lock': {
      id: '/api/release-lock'
      path: '/api/release-lock'
      fullPath: '/api/release-lock'
      preLoaderRoute: typeof ApiReleaseLockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pdf-upload': {
      id: '/api/pdf-upload'
      path: '/api/pdf-upload'
      fullPath: '/api/pdf-upload'
      preLoaderRoute: typeof ApiPdfUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/pricing': {
      id: '/_public/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PublicPricingRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/demo': {
      id: '/_public/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof PublicDemoRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_private/profile': {
      id: '/_private/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof PrivateProfileRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/billing': {
      id: '/_private/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof PrivateBillingRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signout': {
      id: '/_auth/signout'
      path: '/signout'
      fullPath: '/signout'
      preLoaderRoute: typeof AuthSignoutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signin': {
      id: '/_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_private/projects/': {
      id: '/_private/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof PrivateProjectsIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/projects/$projectId': {
      id: '/_private/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof PrivateProjectsProjectIdRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/projects/$projectId_/labelling': {
      id: '/_private/projects/$projectId_/labelling'
      path: '/projects/$projectId/labelling'
      fullPath: '/projects/$projectId/labelling'
      preLoaderRoute: typeof PrivateProjectsProjectIdLabellingRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/projects/$projectId_/entity_types': {
      id: '/_private/projects/$projectId_/entity_types'
      path: '/projects/$projectId/entity_types'
      fullPath: '/projects/$projectId/entity_types'
      preLoaderRoute: typeof PrivateProjectsProjectIdEntity_typesRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/projects/$projectId_/engineering': {
      id: '/_private/projects/$projectId_/engineering'
      path: '/projects/$projectId/engineering'
      fullPath: '/projects/$projectId/engineering'
      preLoaderRoute: typeof PrivateProjectsProjectIdEngineeringRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/projects/$projectId_/documents': {
      id: '/_private/projects/$projectId_/documents'
      path: '/projects/$projectId/documents'
      fullPath: '/projects/$projectId/documents'
      preLoaderRoute: typeof PrivateProjectsProjectIdDocumentsRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/projects/$projectId_/dashboard': {
      id: '/_private/projects/$projectId_/dashboard'
      path: '/projects/$projectId/dashboard'
      fullPath: '/projects/$projectId/dashboard'
      preLoaderRoute: typeof PrivateProjectsProjectIdDashboardRouteImport
      parentRoute: typeof PrivateRoute
    }
  }
}

interface AuthRouteChildren {
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignoutRoute: typeof AuthSignoutRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSigninRoute: AuthSigninRoute,
  AuthSignoutRoute: AuthSignoutRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PrivateRouteChildren {
  PrivateBillingRoute: typeof PrivateBillingRoute
  PrivateProfileRoute: typeof PrivateProfileRoute
  PrivateProjectsProjectIdRoute: typeof PrivateProjectsProjectIdRoute
  PrivateProjectsIndexRoute: typeof PrivateProjectsIndexRoute
  PrivateProjectsProjectIdDashboardRoute: typeof PrivateProjectsProjectIdDashboardRoute
  PrivateProjectsProjectIdDocumentsRoute: typeof PrivateProjectsProjectIdDocumentsRoute
  PrivateProjectsProjectIdEngineeringRoute: typeof PrivateProjectsProjectIdEngineeringRoute
  PrivateProjectsProjectIdEntity_typesRoute: typeof PrivateProjectsProjectIdEntity_typesRoute
  PrivateProjectsProjectIdLabellingRoute: typeof PrivateProjectsProjectIdLabellingRoute
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateBillingRoute: PrivateBillingRoute,
  PrivateProfileRoute: PrivateProfileRoute,
  PrivateProjectsProjectIdRoute: PrivateProjectsProjectIdRoute,
  PrivateProjectsIndexRoute: PrivateProjectsIndexRoute,
  PrivateProjectsProjectIdDashboardRoute:
    PrivateProjectsProjectIdDashboardRoute,
  PrivateProjectsProjectIdDocumentsRoute:
    PrivateProjectsProjectIdDocumentsRoute,
  PrivateProjectsProjectIdEngineeringRoute:
    PrivateProjectsProjectIdEngineeringRoute,
  PrivateProjectsProjectIdEntity_typesRoute:
    PrivateProjectsProjectIdEntity_typesRoute,
  PrivateProjectsProjectIdLabellingRoute:
    PrivateProjectsProjectIdLabellingRoute,
}

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren)

interface PublicRouteChildren {
  PublicDemoRoute: typeof PublicDemoRoute
  PublicPricingRoute: typeof PublicPricingRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicDemoRoute: PublicDemoRoute,
  PublicPricingRoute: PublicPricingRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  PrivateRoute: PrivateRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  ApiPdfUploadRoute: ApiPdfUploadRoute,
  ApiReleaseLockRoute: ApiReleaseLockRoute,
  ApiUploadthingRoute: ApiUploadthingRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
